version: "3.7"

services:
    c-intrisics-demo:
      build: 
        context: .
        dockerfile: DockerFile
      volumes:
        - ../:/app
      environment:
        - TZ=UTC
      tty: true
      networks:
        - piers_dev_network
networks:
  piers_dev_network:
    external: true